apiVersion: batch/v1
kind: CronJob
metadata:
  name: fed-reserve-int-rate-train
spec:
  # Run daily at 02:00 UTC. Adjust as needed for data freshness or cost.
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 900
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trainer
              image: your-registry/fed-reserve-int-rate-predictions:latest
              imagePullPolicy: IfNotPresent
              # The script is the container CMD, but keeping args explicit makes the intent clear.
              args: ["python", "train_interest_rate_model.py"]
              env:
                - name: KAGGLE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: kaggle-credentials
                      key: KAGGLE_USERNAME
                - name: KAGGLE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kaggle-credentials
                      key: KAGGLE_KEY
